version: "3"

networks:
  app-tier:
    driver: bridge

services:
  
  database:
      restart: always
      image: postgres
      volumes:
          - postgres_db:/var/lib/postgresql/data/pgdata
      environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: "${DATABASE}"
          POSTGRES_HOST_AUTH_METHOD: trust

          PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - ${DB_PORT}:5432
      networks:
        - app-tier
      extra_hosts:
        - "host.docker.internal:host-gateway"


  python:
    build: python_script/
    environment:
      DATABASE: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: database
      DB_PORT: 5432
    links:
      - database
    depends_on:
      - database
    volumes_from:
      - database
    networks:
      - app-tier

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 9000:3000
    links:
      - database
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-tier
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_db:
  grafana-data:
